# ======= Expected GH Actions Secrets & Vars =======
## Org Secrets - Set in Org Github Settings
# - SLACK_BOT_API_KEY
# - SLACK_TEAM_ID
# - SSH_PRIVATE_KEY
# - BOT_SIGNING_KEY
## Repo Secrets - MUST be set per Repo in Github Repo Settings
# - RC_REMOTE_WEB_ROOT
# - RC_SSH_HOST
# - RC_SSH_PORT
# - RC_SSH_USER
# - RC_REMOTE_WEB_ROOT
# - RC_SSH_HOST
# - RC_SSH_PORT
# - RC_SSH_USER
# - SLACK_CHANNEL_ID

name: 🔨 Staging Deployment
env:
  DEFAULT_BRANCH: $(jq -r '.pull_request.base.ref' $GITHUB_EVENT_PATH)
  _LINTER_RULES_DIR: .github/linters

# Controls when the workflow will run
on:
  # Triggers the workflow pull request events but only for the default branch
  pull_request:
    branches:
      - rc/*
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-stage:
    # Only run the Job if the PR is closed AND the PR is merged
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: [Large-Runner-Ubuntu]

    # Set permissions
    permissions:
      contents: write
      packages: read
      statuses: write
      pull-requests: write
      issues: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Deployment SSH Key
      - name: Setup Deployment SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.BOT_SIGNING_KEY }}" > ~/.ssh/bot
          touch ~/.ssh/config
          echo "Host *
          AddKeysToAgent yes
          IgnoreUnknown UseKeychain
          UseKeychain yes
          IdentityFile ~/.ssh/bot" > ~/.ssh/config
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/bot

      # Check for uncommitted changes.
      - name: Check for Uncommitted Code on Staging
        run: |
          ssh -i~/.ssh/id_rsa -o StrictHostKeyChecking=no -p${{ secrets.RC_SSH_PORT }} ${{ secrets.RC_SSH_USER }}@${{ secrets.RC_SSH_HOST }} "cd ${{ secrets.RC_REMOTE_WEB_ROOT }} && git status -s" > ~/.ssh/git-status.txt
          if [[ -s ~/.ssh/git-status.txt ]]; then
            exit 1
          fi
        id: check_uncommitted

      # Capture uncommitted code and download patch.
      - name: Capture Uncommitted Code
        if: ${{ failure() && steps.check_uncommitted.outcome == 'failure' }}
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${{ secrets.RC_SSH_PORT }} ${{ secrets.RC_SSH_USER }}@${{ secrets.RC_SSH_HOST }} "
            cd ${{ secrets.RC_REMOTE_WEB_ROOT }}
            git diff > uncommitted_changes.patch
          "
          scp -i ~/.ssh/id_rsa -P ${{ secrets.RC_SSH_PORT }} ${{ secrets.RC_SSH_USER }}@${{ secrets.RC_SSH_HOST }}:${{ secrets.RC_REMOTE_WEB_ROOT }}/uncommitted_changes.patch .
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${{ secrets.RC_SSH_PORT }} ${{ secrets.RC_SSH_USER }}@${{ secrets.RC_SSH_HOST }} "
            cd ${{ secrets.RC_REMOTE_WEB_ROOT }}
            rm -rf uncommitted_changes.patch
          "

      # Apply Patch and commit.
      - name: Apply Patch and Commit
        if: ${{ failure() && steps.check_uncommitted.outcome == 'failure' }}
        env:
          UNCOMMITTED_BRANCH: hotfix/staging/uncommitted-changes_${{github.run_id}}.${{github.run_attempt}}
          GIT_REPO_URL: https://github.com/${{ github.repository }}
        run: |
          git apply uncommitted_changes.patch
          git config core.filemode false && sudo chown -R $(whoami) . && chown -R $(whoami) .
          git config --global gpg.format ssh
          git config --global user.signingkey ~/.ssh/bot
          git config --global commit.gpgsign true
          git config user.name "builtmightybot"
          git config user.email "bot@builtmighty.com"
          git checkout -b ${{ env.UNCOMMITTED_BRANCH }}
          rm -rf uncommitted_changes.patch
          git add .
          git commit -S -m "🚨 Captured ALL Uncommitted Code on Staging"
          git push origin ${{ env.UNCOMMITTED_BRANCH }}

      # Pull in and force hotfix branch as active on staging.
      - name: Pull in and force hotfix branch to staging
        if: ${{ failure() && steps.check_uncommitted.outcome == 'failure' }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_PAT: ${{ secrets.DEPLOY_WORKFLOW_PAT }}
          GIT_REPO_URL: github.com/${{ github.repository }}
          UNCOMMITTED_BRANCH: hotfix/staging/uncommitted-changes_${{github.run_id}}.${{github.run_attempt}}
        run: |
          ssh -i~/.ssh/id_rsa -o StrictHostKeyChecking=no -p${{ secrets.RC_SSH_PORT }} ${{ secrets.RC_SSH_USER }}@${{ secrets.RC_SSH_HOST }} "
            cd ${{ secrets.RC_REMOTE_WEB_ROOT }}
            git reset --hard
            git checkout -b ${{ env.UNCOMMITTED_BRANCH }}
            git pull https://${{ vars.DEPLOY_USER }}:${{ env.DEPLOY_PAT }}@${{ env.GIT_REPO_URL }} ${{ env.UNCOMMITTED_BRANCH }}
          "

      # Post uncommitted changes to Slack channel.
      - name: Post Un-committed Changes to Slack channel
        id: slack_failed
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "*🛑 Deployment Failed*\n============================\nGitHub Action build result: `${{ job.status }}`\nTriggered by: `${{ github.triggering_actor }}`\n${{ github.event.pull_request.html_url || github.event.head_commit.url }} \n\n",
              "blocks": [
                {
                  "type": "divider"
                },
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ vars.DEP_RC_FAIL_HEAD }}",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ vars.DEP_RC_FAIL_BODY }}"
                  }
                },
                {
                  "type": "image",
                  "image_url": "${{ vars.DEP_RC_FAIL_IMAGE }}",
                  "alt_text": "inspiration"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🚩 *Result*: `${{ job.status }}`\n🚀 *Triggered By*: `${{ github.event.pull_request.html_url || github.event.head_commit.url }}`\n🧑‍💻 *User*: `${{ github.triggering_actor }}`\n🔀 *Un-commmitted Branch*: `<${{ env.GIT_REPO_URL }}/tree/${{env.UNCOMMITTED_BRANCH}}|${{env.UNCOMMITTED_BRANCH}}>`"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_API_KEY }}
          UNCOMMITTED_BRANCH: hotfix/uncommitted-changes_${{github.run_id}}.${{github.run_attempt}}
          GIT_REPO_URL: https://github.com/${{ github.repository }}

      # Deploy.
      - name: Deploy to Staging
        if: ${{ success() && steps.check_uncommitted.outcome == 'success' }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_PAT: ${{ secrets.DEPLOY_WORKFLOW_PAT }}
          GIT_REPO_URL: github.com/${{ github.repository }}
        run: |
          ssh -i~/.ssh/id_rsa -o StrictHostKeyChecking=no -p${{ secrets.RC_SSH_PORT }} ${{ secrets.RC_SSH_USER }}@${{ secrets.RC_SSH_HOST }} "
            cd ${{ secrets.RC_REMOTE_WEB_ROOT }}
            git checkout ${{ env.DEFAULT_BRANCH }}
            git reset --hard
            git pull https://${{ vars.DEPLOY_USER }}:${{ env.DEPLOY_PAT }}@${{ env.GIT_REPO_URL }} ${{ env.DEFAULT_BRANCH }}
          "

      # Post to Slack channel.
      - name: Post Success to Slack channel
        id: slack
        if: success()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action Build Result: `${{ job.status }}`\nTriggered by: `${{ github.triggering_actor }}`\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "divider"
                },
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ vars.DEP_RC_SUCC_HEAD }}",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ vars.DEP_RC_SUCC_BODY }}"
                  }
                },
                {
                  "type": "image",
                  "image_url": "${{ vars.DEP_RC_SUCC_IMAGE }}",
                  "alt_text": "inspiration"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✅ *GitHub Action Result*: `${{ job.status }}`\n🧑‍💻 *User*: `${{ github.triggering_actor }}`"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_API_KEY }}
