# Built Mighty Production Deployment
name: 🚀 Production Deployment

on:
  release:
    types: [published]
  workflow_dispatch:
  workflow_call:
    inputs:
      remote_host:
        description: 'Production server hostname'
        required: true
        type: string
      remote_user:
        description: 'Production server SSH user'
        required: true
        type: string
      remote_path:
        description: 'Production server deployment path'
        required: true
        type: string
      remote_port:
        description: 'Production server SSH port'
        required: false
        type: string
        default: '22'
      slack_channel_id:
        description: 'Slack channel ID for notifications'
        required: false
        type: string
        default: ''
      exclude_patterns:
        description: 'Additional rsync exclude patterns (comma-separated)'
        required: false
        type: string
        default: ''
    secrets:
      slack_team_id:
        description: 'Slack team ID for notifications'
        required: false
      ssh_private_key:
        description: 'SSH private key for deployment'
        required: true
      slack_bot_token:
        description: 'Slack bot token for notifications'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ssh_private_key }}
      
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H -p ${{ inputs.remote_port }} ${{ inputs.remote_host }} >> ~/.ssh/known_hosts
      
      - name: Enable maintenance mode
        run: |
          echo "Enabling maintenance mode..."
          ssh -p ${{ inputs.remote_port }} ${{ inputs.remote_user }}@${{ inputs.remote_host }} "touch ${{ inputs.remote_path }}/.maintenance"
          echo "✓ Maintenance mode enabled"
      
      - name: Download previous manifest from production
        id: old-manifest
        run: |
          echo "Checking for previous deployment manifest..."
          if ssh -p ${{ inputs.remote_port }} ${{ inputs.remote_user }}@${{ inputs.remote_host }} "test -f ${{ inputs.remote_path }}/.deployment-manifest.txt"; then
            scp -P ${{ inputs.remote_port }} ${{ inputs.remote_user }}@${{ inputs.remote_host }}:${{ inputs.remote_path }}/.deployment-manifest.txt /tmp/old-manifest.txt
            echo "manifest_exists=true" >> $GITHUB_OUTPUT
            echo "✓ Previous manifest downloaded"
          else
            echo "manifest_exists=false" >> $GITHUB_OUTPUT
            echo "⚠ No previous manifest found (first deployment?)"
          fi
      
      - name: Generate current manifest
        run: |
          echo "Generating current deployment manifest..."
          find . -type f \
            -not -path "*/.git/*" \
            -not -path "*/node_modules/*" \
            -not -path "*/.github/*" \
            -not -name ".gitignore" \
            -not -name ".deployment-manifest.txt" \
            -not -name "deploy.sh" \
            -not -name "README.md" \
            | sed 's|^\./||' \
            | sort > /tmp/new-manifest.txt
          echo "✓ Generated manifest with $(wc -l < /tmp/new-manifest.txt) files"
      
      - name: Compare manifests and remove old files
        if: steps.old-manifest.outputs.manifest_exists == 'true'
        run: |
          echo "Comparing manifests to find removed files..."
          comm -23 /tmp/old-manifest.txt /tmp/new-manifest.txt > /tmp/files-to-remove.txt
          
          if [ -s /tmp/files-to-remove.txt ]; then
            echo "Found $(wc -l < /tmp/files-to-remove.txt) files to remove:"
            cat /tmp/files-to-remove.txt
            
            echo "Removing old files from production..."
            while IFS= read -r file; do
              if ssh -p ${{ inputs.remote_port }} ${{ inputs.remote_user }}@${{ inputs.remote_host }} "rm -f ${{ inputs.remote_path }}/${file}"; then
                echo "  ✓ Removed: ${file}"
              else
                echo "  ✗ Failed to remove: ${file}"
              fi
            done < /tmp/files-to-remove.txt
          else
            echo "✓ No files to remove"
          fi
      
      - name: Build rsync exclude parameters
        id: rsync-excludes
        run: |
          # Base excludes
          EXCLUDES="--exclude=.git/ --exclude=node_modules/ --exclude=.github/ --exclude=.gitignore --exclude=deploy.sh --exclude=.deployment-manifest.txt --exclude=wp-config.php --exclude=wp-content/uploads/ --exclude=.htaccess"
          
          # Add custom excludes if provided
          if [ -n "${{ inputs.exclude_patterns }}" ]; then
            IFS=',' read -ra PATTERNS <<< "${{ inputs.exclude_patterns }}"
            for pattern in "${PATTERNS[@]}"; do
              EXCLUDES="$EXCLUDES --exclude=${pattern}"
            done
          fi
          
          echo "excludes=$EXCLUDES" >> $GITHUB_OUTPUT
      
      - name: Sync files to production
        run: |
          echo "Syncing files to production..."
          rsync -avz \
            ${{ steps.rsync-excludes.outputs.excludes }} \
            -e "ssh -p ${{ inputs.remote_port }}" \
            ./ ${{ inputs.remote_user }}@${{ inputs.remote_host }}:${{ inputs.remote_path }}/
          echo "✓ Files synced"
      
      - name: Upload new manifest to production
        run: |
          echo "Saving deployment manifest to production..."
          scp -P ${{ inputs.remote_port }} /tmp/new-manifest.txt ${{ inputs.remote_user }}@${{ inputs.remote_host }}:${{ inputs.remote_path }}/.deployment-manifest.txt
          echo "✓ Manifest saved"
      
      - name: Deployment summary
        run: |
          echo "================================"
          echo "✓ Deployment complete!"
          echo "================================"
          echo "Server: ${{ inputs.remote_host }}"
          echo "Path: ${{ inputs.remote_path }}"
          echo "Files deployed: $(wc -l < /tmp/new-manifest.txt)"
          if [ -f /tmp/files-to-remove.txt ]; then
            echo "Files removed: $(wc -l < /tmp/files-to-remove.txt)"
          fi
