name: 🧪 Staging Deployment

on:
  pull_request:
    branches:
      - rc/*
    types: [closed]
  workflow_dispatch:

jobs:
  deploy:
    concurrency:
      group: staging-deploy
      cancel-in-progress: false
    if: github.event.pull_request.merged == true
    uses: builtmighty/.github/.github/workflows/deploy.yml@main
    with:
      site_url: ${{ vars.STAGING_URL }}
      environment: 'staging'
    secrets:
      remote_host: ${{ secrets.RC_SSH_HOST }}
      remote_user: ${{ secrets.RC_SSH_USER }}
      remote_path: ${{ secrets.RC_REMOTE_WEB_ROOT }}
      remote_port: ${{ secrets.RC_SSH_PORT }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
      slack_team_id: ${{ secrets.SLACK_TEAM_ID }}
      slack_bot_token: ${{ secrets.SLACK_BOT_API_KEY }}
