

name: Deploy to Staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "refs/heads/rc/*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install WP CLI
        run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp && wp --info

      - name: Install SSH
        run: sudo apt-get install openssh-client

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: 'C05HG205B4K'
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\nTriggered by: ${{ github.triggering_actor }}\n${{ github.event.release.name }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\nTriggered by: ${{ github.triggering_actor }}\n${{ github.event.release.name }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_API_KEY }}


#       - name: Deploy WordPress
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#           SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
#         run: |
#           ssh -i <(echo "$SSH_PRIVATE_KEY") -o StrictHostKeyChecking=no <username>@<hostname> "cd <path/to/wordpress> && wp core update --path=<path/to/wordpress>"

# - name: Run a multi-line script
# run: |
#   echo Add other actions to build,
#   echo test, and deploy your project.

      # - name: Notify Slack
      #   env:
      #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   run: |
      #       curl -X POST -H 'Content-type: application/json' --data '{"text":"A new push has been made to the main branch!"}' $SLACK_WEBHOOK_URL
